---
language: nix
sudo-required: false
cache:
  - $HOME/.stack
matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu

#    - env: TARGET=x86_64-apple-darwin
#      os: osx

install:
  - nix-env -i binutils
  - nix-env -i ats
  - nix-env -i stack
  - |
    if [ `uname` == "Linux" ]
    then
      curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
    else
      echo 'skipping hlint...'
    fi

script:
  - ./shake.hs test
  - mv target/ac ac-$TARGET

deploy:
  api_key:
    secure: "ATyfoUKAkunB+u/PIf4NE0EGg5kH9Fbe7m9fEZYg6Ir4U1WsYTB8AknkwQYu+wU6B/FJd9ohwtIWeeUopeaWDx/EkHJyIYlwxg+zI1cMXci2tBCW66LM7xHK6zFGKpUorJY0LtQikgynf18ek45blqrQ5Wz9FbG7UFpENUk4GV194Gpk+X8elrGoFcjcLsA+jBLIBjlHANP+tCCOidYpLyM6junfJ3cZD2ainlRqW/gGtPQ5N3GP5/vtauGe+Opo/nUehc+eAZEdDthkZFpz6/M+bceuUWRsS7WLbrMRr63vTPNmbGjCnYesS6w1FNG56OexJDxdOeAZyIcy8oMlc2ICaCV9I9Ruk6FV2qP2aPGN8dAxsOieU10GVnMlSvlKkViAF4BIFgNt6h5zPNuob4As8kwx+a8holnfdQyEmn8jX+a5aCJ55xGqmw94p7HWGYfs2rLpvpE3XzFJR3e/YDtwPbLC2n0Td4ppzpx8ztMOD722ZoLrd7jRxjItQFOEwXnZelMouBcboydSVoaWK62jDSLp+pVEfrxG3FfrPWdy+aVf8KE8qk4YVaYid5KcIixBUuatqX+/gGjde62ZMrkToCnF5gMAbrDaSMGt/ylWv/SUnpxmOP/2y7RgDBuajiELdkFrUacl9Or/OMqgmrg6dI4c2A6uth2rhNSLGPU="
  file: ac-$TARGET
  on:
    tags: true
  provider: releases
  skip_cleanup: true
